// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZUs5RwGTkoXLw9z7CIGHyOwPwWm7vTU',
    appId: '1:1098639720426:web:829316482796570bbe3c93',
    messagingSenderId: '1098639720426',
    projectId: 'radz-a77f4',
    authDomain: 'radz-a77f4.firebaseapp.com',
    storageBucket: 'radz-a77f4.firebasestorage.app',
    measurementId: 'G-JLBMVS0WF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrZZsTY91ns9Tlie2iHGxxdcYHa82Kn4',
    appId: '1:1098639720426:android:29aefa8fbbe3dc3cbe3c93',
    messagingSenderId: '1098639720426',
    projectId: 'radz-a77f4',
    storageBucket: 'radz-a77f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HFxTah8pP2EKZgzFoNq34jDp7hYeZZI',
    appId: '1:1098639720426:ios:82301c266f8b8d24be3c93',
    messagingSenderId: '1098639720426',
    projectId: 'radz-a77f4',
    storageBucket: 'radz-a77f4.firebasestorage.app',
    iosBundleId: 'com.example.radzadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HFxTah8pP2EKZgzFoNq34jDp7hYeZZI',
    appId: '1:1098639720426:ios:82301c266f8b8d24be3c93',
    messagingSenderId: '1098639720426',
    projectId: 'radz-a77f4',
    storageBucket: 'radz-a77f4.firebasestorage.app',
    iosBundleId: 'com.example.radzadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZUs5RwGTkoXLw9z7CIGHyOwPwWm7vTU',
    appId: '1:1098639720426:web:69f0407185f269d6be3c93',
    messagingSenderId: '1098639720426',
    projectId: 'radz-a77f4',
    authDomain: 'radz-a77f4.firebaseapp.com',
    storageBucket: 'radz-a77f4.firebasestorage.app',
    measurementId: 'G-8K2FBBJV2S',
  );

}